title: Language and Intelligence Laboratory
subtitle: Moffitt Cancer Center
description: A multidisciplinary research group that translates advances in natural language processing (NLP) and machine learning (ML) to solve problems in oncology and healthcare informatics.
header: images/background.jpg
footer: images/background.jpg
links:
  email: contact@your-lab.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: your-lab
  twitter: YourLabHandle
  instagram: YourLabHandle
  youtube: YourLabChannel
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: contact@hunglongtrangithub.com
github: hunglongtrangithub
twitter: hunglongtrangithub
instagram: hunglongtrangithub
youtube: hunglongtrangithub
